networks:
  default: development
  development:
    gas_limit: auto
    gas_buffer: 1
    gas_price: auto
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings: 
      chain_id: 1
  live:
    gas_limit: auto
    gas_buffer: 1.1
    gas_price: auto
    reverting_tx_gas_limit: false
    default_contract_owner: false

compiler:
  solc:
    version: 0.8.19
    optimizer:
      enabled: true
      runs: 200
    viaIR: true
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.8.0/contracts"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0/contracts"
      - "forge-std/=lib/forge-std/src/"
      - "ds-test/=lib/forge-std/lib/ds-test/src/"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0
dev_deployment_artifacts:
  - true
